name: Build and publish to github repo

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peterhs73/sphinx-docs-action@v0.3.0
        with:
          python-version: 3.8
          docs-source: docs/
          external-repo: peterhs73/sphinx-docs
          deploy-token: ${{secrets.PRIVATE_TOKEN}}